//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by skipper.rc
//
#define ID_REMOVE_LINK                  3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_SPELL_CHECKER               201
#define IDR_SKIPPER_CONTEX              204
#define IDD_HYPER_LINK_DLG              205
#define IDD_NEW_FILENAME                206
#define IDD_PAGE_SETUP                  208
#define IDR_MENUBAR                     209
#define IDD_SPELL_EDIT                  210
#define IDD_OPTIONS                     211
#define IDD_OPEN_FILE_DLG               212
#define IDB_LISTICON                    213
#define IDD_OPENFILE_DLG                214
#define IDD_EMBOSS_DLG                  215
#define IDD_EMBOSS_PROP_DLG             217
#define IDD_NEWFILE_DLG                 218
#define IDD_FIND_DLG                    219
#define IDD_REPLACE_DLG                 220
#define IDD_FILE_OPERATIONS             221
#define ID_FILE_OPERATIONS              221
#define IDD_COPIES_DLG                  222
#define IDD_BRFWARNING_DLG              223
#define IDEDT_NOT_IN_DICTIONARY         1000
#define IDCLBX_SUGGESTIONS              1001
#define IDBTN_IGNORE                    1002
#define IDBTN_IGNORE_ALL                1003
#define IDBTN_ADD                       1004
#define IDBTN_CHANGE                    1005
#define IDBTN_CHANGE_ALL                1006
#define IDBTN_SUGGEST                   1007
#define IDEDT_TEXT                      1008
#define IDSTA_ERROR_MSG                 1009
#define IDEDT_CHANGE_TO                 1010
#define IDC_RADIO1                      1011
#define IDC_RADIO2                      1012
#define IDC_RADIO3                      1013
#define IDC_RADIO4                      1014
#define IDC_TEXT_TO_DISPLAY             1015
#define IDC_FILE_TO_LINK_TO             1016
#define IDC_SELECTION_OF_FILES          1017
#define IDEDT_NEW_NAME                  1018
#define IDCHK_BRL_FILE                  1019
#define IDCBX_FILE_TYPE                 1020
#define IDEDT_PAGE_HEIGHT               1021
#define IDEDT_PAGE_WIDTH                1022
#define IDEDT_MARGIN_TOP                1023
#define IDEDT_MARGIN_BOTTOM             1024
#define IDEDT_MARGIN_LEFT               1025
#define IDEDT_MARGIN_RIGHT              1026
#define IDSPN_PAGE_HEIGHT               1027
#define IDSPN_PAGE_WIDTH                1028
#define IDSPN_MARGIN_TOP                1029
#define IDSPN_MARGIN_BOTTOM             1030
#define IDSPN_MARGIN_LEFT               1031
#define IDSPN_MARGIN_RIGHT              1032
#define IDRAD_NONE                      1033
#define IDRAD_ARABIC                    1034
#define IDRAD_ROMAN                     1035
#define IDSTA_MESUREMENTS               1036
#define IDLST_EDITOR                    1037
#define IDBTN_ADD_WORD                  1038
#define IDBTN_DELETE                    1039
#define IDBTN_RESORT                    1040
#define IDEDT_LISTEDITCTRL              1041
#define IDBTN_EDIT                      1042
#define IDM_SETBOOKMARK                 1043
#define IDXBX_WORDWRAP                  1044
#define IDCBX_PARA_NUMBERING            1045
#define IDCBX_SCRATCH_PAD_LINE_DIVIDER  1046
#define IDCBX_DATE_TIME_FORMAT          1047
#define IDXBOX_BRAILL2                  1048
#define IDC_CUSTOM                      1050
#define IDEDT_FILENAME                  1051
#define IDC_LSTFILE                     1052
#define IDEDIT_FILETYPE                 1053
#define IDCBX_LOOKIN                    1054
#define IDCBX_FOLDERS                   1055
#define IDLST_FILES                     1056
#define IDEDT_FILE                      1057
#define IDCBX_TYPE                      1058
#define IDC_CHECK_GRADE2_E              1060
#define IDC_CHECK_EMPHASIZED_TXT_E      1061
#define IDC_BUTTON_PROPERTIES_E         1065
#define IDC_EDIT_FROM_E                 1066
#define IDC_BUTTON_CONNECTION           1066
#define IDC_EDIT_TO_E                   1067
#define IDC_EDIT_NUMCOPIES_E            1068
#define IDC_SPIN_NUMCOPIES              1069
#define IDC_STATIC_NUMCOPIES_E          1070
#define IDC_GROUPBOX_PAGERANGE_E        1071
#define IDC_RADIO_ALLPAGES_E            1072
#define IDC_RADIO_PAGES_E               1073
#define IDC_STATIC_FROM_E               1074
#define IDC_STATIC_TO_E                 1075
#define IDC_COMBO_CONNECTION_E          1076
#define IDC_COMBO_PRINTERNAME           1077
#define IDC_COMBO_EMBOSSER_E            1078
#define IDC_EMBOSS_CONNECTION_DLG       1078
#define IDC_EDIT_CELLS_E                1079
#define IDC_EDIT_LINES_E                1080
#define IDC_EDIT_TOP_MARGIN_E           1081
#define IDC_EDIT_MAX_CELLS_E            1082
#define IDC_EDIT_MAX_LINES_E            1083
#define IDC_CHECK_INTERPOINT_PAGES_E    1084
#define IDC_CHECK_INTERPOINT_MARGINS_E  1085
#define IDC_EDIT_LEFT_MARGIN_E          1086
#define IDC_PORT_LOC_EDIT               1088
#define IDC_STATIC_EMBOSSER_E           1089
#define IDC_STATIC_CELLS_E              1090
#define IDC_STATIC_LINES_PER_PAGE_E     1091
#define IDC_STATIC_LINES_E              1092
#define IDC_STATIC_TOP_MARGIN_E         1093
#define IDC_STATIC_CONNECTION_E         1094
#define IDC_STATIC_PRINTERNAME          1095
#define IDC_STATIC_NETWORK              1096
#define IDC_STATIC_CELLS_PER_LINE_E     1097
#define IDC_STATIC_MAX_CELLS_E          1098
#define IDC_STATIC_MAX_LINES_E          1099
#define IDCBX_LOCATION                  1100
#define IDC_STATIC_LEFT_MARGIN_E        1100
#define IDCBX_INSERT_AS                 1102
#define IDC_ASK_GRADE_TWO               1103
#define ID_CHECK_MATCH_CASE             1104
#define ID_CHECK_MATCH_WHOLE            1105
#define ID_GROUP_DIRECTION              1106
#define ID_BUTTON_UP                    1107
#define ID_BUTTON_DOWN                  1108
#define ID_BUTTON_REPLACE               1109
#define ID_BUTTON_REPLACEALL            1110
#define BTN_ADV_FILE_OP                 1111
#define CKX_FILE_TYPE_TXT               1112
#define CKX_FILE_TYPE_RTF               1113
#define CKX_FILE_TYPE_PWD               1114
#define IDC_NUM_OF_COPIES               1115
#define IDCHK_DONOTSHOW                 1116
#define IDSTA_CONVERTBRF_MSG            1117
#define IDCKB_AUTOSAVE                  1118
#define IDC_PRINT_DOUBLE_SPACE          1119
#define ID_OPTIONS_CANCEL               1120
#define ID_EMBOSS_CANCEL                1121
#define ID_COPIES_CANCEL                1122
#define IDM_TOOLS_SPELLCHECKER          32772
#define ID_MARK_WORD                    32773
#define ID_MARK_SENTENCE                32774
#define ID_MARK_PARA                    32775
#define ID_MARK_LINE                    32776
#define ID_MARK_DOC                     32777
#define ID_EDIT_SETMARK                 32778
#define ID_EDIT_CLEARMARK               32779
#define ID_EDIT_MOVETOMARK              32780
#define ID_FONT_BOLD                    32781
#define ID_FONT_ITALIC                  32782
#define ID_FONT_UNDERLINE               32783
#define ID_FONT_STRIKETHROUGH           32784
#define ID_FONT_MORE                    32785
#define ID_PARA_ALIGNLEFT               32786
#define ID_PARA_ALIGNCENTER             32787
#define ID_PARA_ALIGNRIGHT              32788
#define ID_PARA_JUSTIFY                 32789
#define ID_PARA_INCREASEINDENT          32790
#define ID_PARA_DECREASEINDENT          32791
#define ID_PARA_NUMBERING_NONE          32792
#define ID_PARA_NUMBERING_NUMBERPAREN   32793
#define ID_PARA_NUMBERING_NUMBERPERIOD  32794
#define ID_PARA_NUMBERING_PARENNUMBERPAREN 32795
#define ID_PARA_NUMBERING_UCPAREN       32796
#define ID_PARA_NUMBERING_UCPERIOD      32797
#define ID_PARA_NUMBERING_PARENUCPAREN  32798
#define ID_PARA_NUMBERING_LCPAREN       32799
#define ID_PARA_NUMBERING_LCPERIOD      32800
#define ID_PARA_NUMBERING_PARENLCPAREN  32801
#define ID_PARA_NUMBERING_UROMANPAREN   32802
#define ID_PARA_NUMBERING_UROMANPERIOD  32803
#define ID_PARA_NUMBERING_PARENUROMANPAREN 32804
#define ID_PARA_NUMBERING_LROMANPAREN   32805
#define ID_PARA_NUMBERING_LROMANPERIOD  32806
#define ID_PARA_NUMBERING_PARENLROMANPAREN 32807
#define ID_PARA_NUMBERING_BULLET        32808
#define ID_INSERT_D_MMMMDDYYYY          32809
#define ID_INSERT_D_DDMMMMYYYY          32810
#define ID_INSERT_D_MMDDYYYY            32811
#define ID_INSERT_D_DDMMYY              32812
#define ID_INSERT_D_NUM_MDY             32813
#define ID_INSERT_T_ADDTODATE           32814
#define ID_INSERT_T_SECONDS             32815
#define ID_INSERT_T_TWELEVE             32816
#define ID_INSERT_T_TWENTYFOUR          32817
#define ID_INSERT_LINK                  32818
#define ID_FILE_RECENTFILES             32819
#define IDM_FILE_RECENT_FILES           32820
#define ID_CONTEXTMENU                  32821
#define ID_INSERT_AUTODETECT            32822
#define ID_FILE_SCRATCH_PAD             32823
#define ID_FILE_EMBROSS                 32825
#define IDR_FORMAT_PAGE_SETUP           32826
#define IDR_MENU_BAR                    32827
#define IDS_TOOLS                       32828
#define IDS_CAP_MENU                    32830
#define IDS_MENU                        32831
#define ID_MENU_MAIN                    32833
#define IDS_FILE                        32835
#define IDM_FILE                        32836
#define IDM_EDIT                        32837
#define IDS_EDIT                        32838
#define IDM_FORMAT                      32839
#define IDS_FORMAT                      32840
#define IDM_INSERT                      32841
#define IDS_INSERT                      32842
#define IDM_TOOLS                       32843
#define IDM_HELP                        32844
#define IDS_HELP                        32845
#define IDM_TOOLS_INSERT_FILE           32846
#define IDM_FORMAT_WORDWRAP             32847
#define IDM_TOOL_SPELL_EDIT             32848
#define IDM_TOOLS_SPELL_EDIT            32849
#define ID_BM_SETBOOKMARK               32850
#define ID_BM_DELETEBOOKMARK            32851
#define ID_BM_MOVE_BOOKMARK_NEXT        32852
#define ID_BM_MOVE_BOOKMARK_PREV        32853
#define IDM_TOOLS_WORD_COUNT            32854
#define IDM_EDIT_SELECT_TEXT            32855
#define IDM_FILE_REVERT_TO_SAVE         32856
#define IDM_TOOLS_OPTIONS               32857
#define IDM_INSERT_DATE_TIME            32858
#define IDM_INSERT_BULLET_NUMBER        32859
#define IDM_FILE_PRINT                  32860
#define ID_EDIT_SELECTTOMARK            32862
#define ID_SELECT_WORD                  32863
#define ID_SELECT_SENTENCE              32864
#define ID_SELECT_PARA                  32865
#define ID_SELECT_LINE                  32866
#define ID_SELECT_DOC                   32867
#define ID_GOTO_QUERY                   32869
#define ID_GOTO_MOVE                    32870
#define ID_GOTO_QUERY2                  32872
#define ID_MYNEW_ACC                    32873
#define ID_SETPARAGRAPH_DOUBLESPACE     32874
#define IDS_MEASURE_IS_BRAILLE          61216
#define IDS_MEASURE_IS_INCHES           61217
#define IDS_BRAILLE                     61218
#define IDS_INCHES                      61219
#define IDS_BRAILLE_FORMAT              61220
#define IDS_INCHES_FORMAT               61221
#define IDS_RECENT_FILES                61226
#define IDS_SCRATCH_PAD                 61227
#define IDS_SKIPPER_TEXT                61228
#define IDS_BRIALLE_TEXT                61229
#define IDS_BRF_TEXT                    61230
#define IDS_RICH_TEXT                   61231
#define IDS_WORD_TEXT                   61232
#define IDS_ANSI_TEXT                   61233
#define IDS_ALL_FILES                   61234
#define IDS_WORD_TEMPLATE               61235
#define IDS_ALL_FILES_FOLDER            61250
#define IDS_BUSINESS_FOLDER             61251
#define IDS_PERSONAL_FOLDER             61252
#define IDS_STARTUP_FOLDER              61253
#define IDS_TEMPLATES_FOLDER            61254
#define IDS_NONE                        61255
#define IDS_BUSINESS_PATH               61270
#define IDS_PERSONAL_PATH               61271
#define IDS_STARTUP_PATH                61272
#define IDS_TEMPLATES_PATH              61273
#define IDS_MY_DOCUMENTS                61274
#define IDS_MAIN_MEMORY                 61275
#define IDS_ERR_NO_STORAGE              61276
#define IDS_ERR_NO_FOLDER               61277
#define IDS_SKIPPER_EXT                 61285
#define IDS_BRAILLE_EXT                 61286
#define IDS_BRF_EXT                     61287
#define IDS_RICH_EXT                    61288
#define IDS_WORD_EXT                    61289
#define IDS_ANSI_EXT                    61290
#define IDS_ALL_FILES_EXT               61291
#define IDS_WORD_TEMPLATE_EXT           61292
#define IDS_TITLE_WORD_COUNT            61330
#define IDS_CAPITALIZATION_ERROR        61403
#define IDS_BEGIN_WITH_NUMERAL          61404
#define IDS_NO_SUGGESTIONS              61405
#define IDS_REPEAT_WORD                 61406
#define IDS_UNKNOWN_INPUT_WORD          61407
#define IDS_ABBREVIATION                61408
#define IDS_CHANGED_ONCE                61409
#define IDS_CHANGE_ALWAYS               61410
#define IDS_AUTO_REPLACE                61411
#define IDS_UNKNOWN_ERRROR              61412
#define IDS_NO_ERRORS_FOUND             61413
#define IDS_SPELLCHECKER                61414
#define IDS_MRU_RECENT_FILE             61415
#define IDS_MENU_RECENT_FILE            61416
#define IDS_MENU_FILE                   61417
#define IDS_SAVE_FILE                   61418
#define IDS_FINISHED_DOCUMENT           61419
#define IDS_INVALID_FILE_NAME           61420
#define IDS_INVALID_VALUE_ENTERED       61421
#define IDS_BRAILLE_LPP                 61422
#define IDS_BRAILLE_LSPP                61423
#define IDS_BRAILLE_CELLS               61424
#define IDS_BRAILLE_CELL                61425
#define IDS_NO_BRAILLE_INCHE            61426
#define IDS_NO_BRAILLE_INCHES           61428
#define IDS_WORDS_COUNTED               61429
#define IDS_TITLE_REVERT_TO_SAVE        61431
#define IDS_REVERT_TO_SAVE              61432
#define IDS_PRINTDLG_ERROR_TITLE        61433
#define IDS_NOPORTS                     61434
#define IDS_NOPRINTERS                  61435
#define IDS_PRINTERNOTFOUND             61436
#define IDS_PRINTDLG_DEFAULT            61437
#define IDS_CREATEDCFAILURE             61438
#define IDS_CLOSE_LABEL                 61439
#define IDS_EMB_NETWORK_DEVICE_LABEL    61440
#define IDS_EMB_WAIT_MSG                61441
#define IDS_EMB_ERR_COMMUNICATION       61442
#define IDS_CANT_OPEN_PORT              61443
#define IDS_EMB_CELLS_TOO_HIGH          61444
#define IDS_EMB_LINES_TOO_HIGH          61445
#define IDS_NONE_FOUND                  61446
#define IDS_WAIT_GENERIC_TITLE          61447
#define IDS_BRF_ERR_TRANS               61448
#define IDS_ERR_UNKNOWN                 61449
#define IDS_FINISHED_SEARCH             61452
#define IDS_APP_NAME                    61453
#define IDS_INSERT_AS_TEXT              61454
#define IDS_INSERT_AS_G2BRL             61455
#define IDS_NEW_FILE                    61456
#define IDS_GRADE2                      61457
#define IDS_CONTINUE_SPELL_CHECK        61458
#define IDS_CONVERTBRF                  61459
#define IDS_ERR_FILETOLARGE             61460
#define IDS_CONVERT_ABORT               61461
#define IDS_FILE_SAVED                  61462
#define IDS_NOTIFICATION                61463
#define IDS_EMB_ERR_COMMUNICATION_RETRY 61464
#define IDS_STRING_TOO_LARGE            61465
#define IDS_FILE_READONLY               61466
#define IDS_FILE_READONLY_MSG           61467
#define IDS_LINE_COL_POSITION           61468
#define IDS_LINE_COL_POSITION2          61469
#define IDS_INVALID_GOTOMOVE            61470
#define IDS_FSEDIT_WINFILE_INFO         61471
#define IDS_FILE_INUSEBY_OTHER_FSEDIT   61472
#define IDS_FILE_NOLONGER_EXISTS        61473

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32875
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
