
//GENERAL ERROR CODES
#define ERR_GRL_UNKNOWN         -100

// BRAILLE ERROR CODES
#define ERR_BRF_TRANSLATION     -200

// EMBOSSER ERROR CODES
#define ERR_EMB_PORT			-220
#define ERR_EMB_COMMUNICATION   -221
#define ERR_EMB_COMMUNICATION_RETRY -222

